INSERT INTO meets (name, location, date) VALUES ('Try Outs', 'Home', '2020-01-21');
INSERT INTO meets (name, location, date) VALUES ('Bosco-St. Joseph', 'Home', '2020-02-24');
INSERT INTO meets (name, location, date) VALUES ('San Pedro', 'Away', '2020-02-27');
INSERT INTO meets (name, location, date) VALUES ('Beverly Hills', 'Home', '2020-03-04');
INSERT INTO meets (name, location, date) VALUES ('Palos Verdes', 'Away', '2020-03-09');
INSERT INTO meets (name, location, date) VALUES ('Carson', 'Home', '2020-03-18');
INSERT INTO meets (name, location, date) VALUES ('El Segundo', 'Away', '2020-03-24');
INSERT INTO meets (name, location, date) VALUES ('FNL Invite', 'Home', '2020-03-27');
INSERT INTO meets (name, location, date) VALUES ('Torrance', 'Home', '2020-03-31');
INSERT INTO meets (name, location, date) VALUES ('North', 'Home', '2020-04-13');
INSERT INTO meets (name, location, date) VALUES ('South', 'Home', '2020-04-22');
INSERT INTO meets (name, location, date) VALUES ('League Prelims', 'Home', '2020-04-28');
INSERT INTO meets (name, location, date) VALUES ('League Finals', 'Home', '2020-04-30');
